### ISSUE TITLE
Issues with VF components

### ISSUE THREAD

**Issue by m4rc1e** [Lorp/samsa#18] opened 2020-03-17 16:12 UTC
This is a pretty cool tool. I'm impressed with the amount of features given you've written this yourself.

Whilst inspecting a font, I noticed some components appear off.

<img width="1280" alt="Screenshot 2020-03-17 at 16 07 21" src="https://user-images.githubusercontent.com/7525512/76876387-c4278300-6869-11ea-87c7-10f6059295ad.png">

I've attached the font and the gid you want to inspect is 138

[Oswald-VF.ttf.zip](https://github.com/Lorp/samsa/files/4344426/Oswald-VF.ttf.zip)

**Comment by Lorp** [comment] 2020-03-17 18:04
Thanks for the report, Marc. Glad you’re enjoying the tool :)

This is in fact a duplicate of the component nesting issue #13. I’ll get to it soon.

**Closed** 2020-03-17 20:45 UTC
